# Generated by Django 4.0.2 on 2022-02-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'Securities'},
        ),
        migrations.AlterModelOptions(
            name='securityassetclass',
            options={'verbose_name': 'Security Asset Class', 'verbose_name_plural': 'Security Asset Classes'},
        ),
    ]
